
spring:
  application:
    name: notification-service
  cloud:
    stream:
      bindings:
        notificationEventSupplier-in-0:
          destination: notification-events
  sleuth:
    integration:
      enabled: true
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 0

eureka:
  instance:
    preferIpAdress: true
    instance-id: ${spring.application.name}:${random.uuid}